// Imported first by server.ts: loads .env and makes sure every secret exists
// before any module reads it. Missing secrets are generated once and saved
// to the git-ignored .env files; in production they must be provided.
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';

const FRONTEND_ENV = path.resolve(process.cwd(), '.env');
const BACKEND_ENV = path.resolve(process.cwd(), '..', 'backend', '.env');

dotenv.config({ path: FRONTEND_ENV, quiet: true } as any);

const random = () => crypto.randomBytes(48).toString('base64url');

function ed25519Pem(): string {
  const { privateKey } = crypto.generateKeyPairSync('ed25519');
  return Buffer.from(privateKey.export({ type: 'pkcs8', format: 'pem' }) as string).toString('base64');
}

// name -> [generator, also needed by the Python engine]
const SECRETS: Record<string, [() => string, boolean]> = {
  JWT_SECRET: [random, false],
  HMAC_SECRET: [random, false],
  ENGINE_API_KEY: [random, true],
  PII_HASH_KEY: [random, true],
  ANCHOR_SIGNING_KEY: [ed25519Pem, false],
};

function readEnv(file: string): Record<string, string> {
  if (!fs.existsSync(file)) return {};
  return dotenv.parse(fs.readFileSync(file));
}

function append(file: string, lines: string[]) {
  const prefix = fs.existsSync(file) && !fs.readFileSync(file, 'utf8').endsWith('\n') ? '\n' : '';
  fs.appendFileSync(file, `${prefix}\n# Generated by server/bootstrap-secrets.ts — keep private, never commit\n${lines.join('\n')}\n`);
}

const missing = Object.keys(SECRETS).filter((k) => !process.env[k]);
if (missing.length) {
  if (process.env.NODE_ENV === 'production') {
    console.error(`Refusing to start: missing secrets ${missing.join(', ')}. Set them in the environment.`);
    process.exit(1);
  }
  const backendEnv = readEnv(BACKEND_ENV);
  const frontLines: string[] = [];
  const backLines: string[] = [];
  for (const key of missing) {
    const [make, shared] = SECRETS[key];
    // Reuse a shared key the engine already has, so both sides agree.
    const value = shared && backendEnv[key] ? backendEnv[key] : make();
    process.env[key] = value;
    frontLines.push(`${key}=${value}`);
    if (shared && !backendEnv[key]) backLines.push(`${key}=${value}`);
  }
  append(FRONTEND_ENV, frontLines);
  if (backLines.length && fs.existsSync(path.dirname(BACKEND_ENV))) append(BACKEND_ENV, backLines);
  console.log(`Generated missing secrets (${missing.join(', ')}) and saved them to .env` +
    (backLines.length ? ' and backend/.env' : ''));
}
